local function _1_(...)
  local M_3_auto
  local function _2_()
    vim.api.nvim_set_hl(0, "Normal", {fg = "#abb2bf", bg = "#282c34"})
    vim.api.nvim_set_hl(0, "Terminal", {fg = "#abb2bf", bg = "#282c34"})
    vim.api.nvim_set_hl(0, "EndOfBuffer", {fg = "#282c34", bg = "#282c34"})
    vim.api.nvim_set_hl(0, "FoldColumn", {fg = "#abb2bf", bg = "#31353f"})
    vim.api.nvim_set_hl(0, "Folded", {fg = "#abb2bf", bg = "#31353f"})
    vim.api.nvim_set_hl(0, "SignColumn", {fg = "#abb2bf", bg = "#282c34"})
    vim.api.nvim_set_hl(0, "ToolbarLine", {fg = "#abb2bf"})
    vim.api.nvim_set_hl(0, "Cursor", {reverse = true})
    vim.api.nvim_set_hl(0, "vCursor", {reverse = true})
    vim.api.nvim_set_hl(0, "iCursor", {reverse = true})
    vim.api.nvim_set_hl(0, "lCursor", {reverse = true})
    vim.api.nvim_set_hl(0, "CursorIM", {reverse = true})
    vim.api.nvim_set_hl(0, "CursorColumn", {bg = "#31353f"})
    vim.api.nvim_set_hl(0, "CursorLine", {bg = "#31353f"})
    vim.api.nvim_set_hl(0, "ColorColumn", {bg = "#31353f"})
    vim.api.nvim_set_hl(0, "CursorLineNr", {fg = "#abb2bf"})
    vim.api.nvim_set_hl(0, "LineNr", {fg = "#5c6370"})
    vim.api.nvim_set_hl(0, "Conceal", {fg = "#5c6370", bg = "#31353f"})
    vim.api.nvim_set_hl(0, "DiffAdd", {fg = "none", bg = "#31392b"})
    vim.api.nvim_set_hl(0, "DiffChange", {fg = "none", bg = "#1c3448"})
    vim.api.nvim_set_hl(0, "DiffDelete", {fg = "none", bg = "#382b2c"})
    vim.api.nvim_set_hl(0, "DiffText", {fg = "none", bg = "#2c5372"})
    vim.api.nvim_set_hl(0, "DiffAdded", {fg = "#98c379"})
    vim.api.nvim_set_hl(0, "DiffRemoved", {fg = "#e86671"})
    vim.api.nvim_set_hl(0, "DiffFile", {fg = "#56b6c2"})
    vim.api.nvim_set_hl(0, "DiffIndexLine", {fg = "#5c6370"})
    vim.api.nvim_set_hl(0, "Directory", {fg = "#61afef"})
    vim.api.nvim_set_hl(0, "ErrorMsg", {fg = "#e86671", bold = true})
    vim.api.nvim_set_hl(0, "WarningMsg", {fg = "#e5c07b", bold = true})
    vim.api.nvim_set_hl(0, "MoreMsg", {fg = "#61afef", bold = true})
    vim.api.nvim_set_hl(0, "IncSearch", {fg = "#282c34", bg = "#d19a66"})
    vim.api.nvim_set_hl(0, "Search", {fg = "#282c34", bg = "#ebd09c"})
    vim.api.nvim_set_hl(0, "Substitute", {fg = "#282c34", bg = "#98c379"})
    vim.api.nvim_set_hl(0, "MatchParen", {fg = "none", bg = "#5c6370"})
    vim.api.nvim_set_hl(0, "NonText", {fg = "#5c6370"})
    vim.api.nvim_set_hl(0, "Whitespace", {fg = "#5c6370"})
    vim.api.nvim_set_hl(0, "SpecialKey", {fg = "#5c6370"})
    vim.api.nvim_set_hl(0, "Pmenu", {fg = "#abb2bf", bg = "#31353f"})
    vim.api.nvim_set_hl(0, "PmenuSbar", {fg = "none", bg = "#31353f"})
    vim.api.nvim_set_hl(0, "PmenuSel", {fg = "#282c34", bg = "#73b8f1"})
    vim.api.nvim_set_hl(0, "WildMenu", {fg = "#282c34", bg = "#61afef"})
    vim.api.nvim_set_hl(0, "PmenuThumb", {fg = "none", bg = "#5c6370"})
    vim.api.nvim_set_hl(0, "Question", {fg = "#e5c07b"})
    vim.api.nvim_set_hl(0, "SpellBad", {fg = "#e86671", underline = true, sp = "#e86671"})
    vim.api.nvim_set_hl(0, "SpellCap", {fg = "#e5c07b", underline = true, sp = "#e5c07b"})
    vim.api.nvim_set_hl(0, "SpellLocal", {fg = "#61afef", underline = true, sp = "#61afef"})
    vim.api.nvim_set_hl(0, "SpellRare", {fg = "#c678dd", underline = true, sp = "#c678dd"})
    vim.api.nvim_set_hl(0, "StatusLine", {fg = "#abb2bf", bg = "#393f4a"})
    vim.api.nvim_set_hl(0, "StatusLineTerm", {fg = "#abb2bf", bg = "#393f4a"})
    vim.api.nvim_set_hl(0, "StatusLineNC", {fg = "#5c6370", bg = "#31353f"})
    vim.api.nvim_set_hl(0, "StatusLineTermNC", {fg = "#5c6370", bg = "#31353f"})
    vim.api.nvim_set_hl(0, "TabLine", {fg = "#abb2bf", bg = "#31353f"})
    vim.api.nvim_set_hl(0, "TabLineFill", {fg = "#5c6370", bg = "#31353f"})
    vim.api.nvim_set_hl(0, "TabLineSel", {fg = "#282c34", bg = "#abb2bf"})
    vim.api.nvim_set_hl(0, "VertSplit", {fg = "#3b3f4c"})
    vim.api.nvim_set_hl(0, "Visual", {bg = "#3b3f4c"})
    vim.api.nvim_set_hl(0, "VisualNOS", {fg = "none", bg = "#393f4a", underline = true})
    vim.api.nvim_set_hl(0, "QuickFixLine", {fg = "#61afef", underline = true})
    vim.api.nvim_set_hl(0, "Debug", {fg = "#e5c07b"})
    vim.api.nvim_set_hl(0, "debugPC", {fg = "#282c34", bg = "#98c379"})
    vim.api.nvim_set_hl(0, "debugBreakpoint", {fg = "#282c34", bg = "#e86671"})
    vim.api.nvim_set_hl(0, "ToolbarButton", {fg = "#282c34", bg = "#73b8f1"})
    vim.api.nvim_set_hl(0, "FloatBorder", {fg = "#5c6370", bg = "#31353f"})
    vim.api.nvim_set_hl(0, "NormalFloat", {fg = "#abb2bf", bg = "#31353f"})
    return true
  end
  local function _3_()
    vim.api.nvim_set_hl(0, "Normal", {fg = "#5c6370"})
    return true
  end
  M_3_auto = {common = _2_, other = _3_}
  local function _4_()
    do local _ = (M_3_auto).common end
    return (M_3_auto).other
  end
  M_3_auto["colorscheme"] = _4_
  return M_3_auto
end
return _1_(...)
