local function _1_(...)
  local M_3_auto
  local function _2_()
    vim.api.nvim_set_hl(0, "CmpItemAbbr", {fg = "#abb2bf"})
    vim.api.nvim_set_hl(0, "CmpItemAbbrDeprecated", {fg = "#848b98", strikethrough = true})
    vim.api.nvim_set_hl(0, "CmpItemAbbrMatch", {fg = "#56b6c2"})
    vim.api.nvim_set_hl(0, "CmpItemAbbrMatchFuzzy", {fg = "#56b6c2", underline = true})
    vim.api.nvim_set_hl(0, "CmpItemMenu", {fg = "#848b98"})
    vim.api.nvim_set_hl(0, "CmpItemKind", {fg = "#c678dd"})
    vim.api.nvim_set_hl(0, "CmpItemKindDefault", {fg = "#c678dd"})
    vim.api.nvim_set_hl(0, "CmpItemKindClass", {fg = "#e5c07b"})
    vim.api.nvim_set_hl(0, "CmpItemKindColor", {fg = "#98c379"})
    vim.api.nvim_set_hl(0, "CmpItemKindConstant", {fg = "#d19a66"})
    vim.api.nvim_set_hl(0, "CmpItemKindConstructor", {fg = "#61afef"})
    vim.api.nvim_set_hl(0, "CmpItemKindEnum", {fg = "#c678dd"})
    vim.api.nvim_set_hl(0, "CmpItemKindEnumMember", {fg = "#e5c07b"})
    vim.api.nvim_set_hl(0, "CmpItemKindEvent", {fg = "#e5c07b"})
    vim.api.nvim_set_hl(0, "CmpItemKindField", {fg = "#c678dd"})
    vim.api.nvim_set_hl(0, "CmpItemKindFile", {fg = "#61afef"})
    vim.api.nvim_set_hl(0, "CmpItemKindFolder", {fg = "#d19a66"})
    vim.api.nvim_set_hl(0, "CmpItemKindFunction", {fg = "#61afef"})
    vim.api.nvim_set_hl(0, "CmpItemKindInterface", {fg = "#98c379"})
    vim.api.nvim_set_hl(0, "CmpItemKindKeyword", {fg = "#56b6c2"})
    vim.api.nvim_set_hl(0, "CmpItemKindMethod", {fg = "#61afef"})
    vim.api.nvim_set_hl(0, "CmpItemKindModule", {fg = "#d19a66"})
    vim.api.nvim_set_hl(0, "CmpItemKindOperator", {fg = "#e86671"})
    vim.api.nvim_set_hl(0, "CmpItemKindProperty", {fg = "#56b6c2"})
    vim.api.nvim_set_hl(0, "CmpItemKindReference", {fg = "#d19a66"})
    vim.api.nvim_set_hl(0, "CmpItemKindSnippet", {fg = "#e86671"})
    vim.api.nvim_set_hl(0, "CmpItemKindStruct", {fg = "#c678dd"})
    vim.api.nvim_set_hl(0, "CmpItemKindText", {fg = "#848b98"})
    vim.api.nvim_set_hl(0, "CmpItemKindTypeParameter", {fg = "#e86671"})
    vim.api.nvim_set_hl(0, "CmpItemKindUnit", {fg = "#98c379"})
    vim.api.nvim_set_hl(0, "CmpItemKindValue", {fg = "#d19a66"})
    vim.api.nvim_set_hl(0, "CmpItemKindVariable", {fg = "#c678dd"})
    return true
  end
  local function _3_()
    vim.api.nvim_set_hl(0, "Normal", {fg = "#abb2bf", bg = "#282c34"})
    vim.api.nvim_set_hl(0, "Terminal", {fg = "#abb2bf", bg = "#282c34"})
    vim.api.nvim_set_hl(0, "EndOfBuffer", {fg = "#282c34", bg = "#282c34"})
    vim.api.nvim_set_hl(0, "FoldColumn", {fg = "#abb2bf", bg = "#31353f"})
    vim.api.nvim_set_hl(0, "Folded", {fg = "#abb2bf", bg = "#31353f"})
    vim.api.nvim_set_hl(0, "SignColumn", {fg = "#abb2bf", bg = "#282c34"})
    vim.api.nvim_set_hl(0, "ToolbarLine", {fg = "#abb2bf"})
    vim.api.nvim_set_hl(0, "Cursor", {reverse = true})
    vim.api.nvim_set_hl(0, "vCursor", {reverse = true})
    vim.api.nvim_set_hl(0, "iCursor", {reverse = true})
    vim.api.nvim_set_hl(0, "lCursor", {reverse = true})
    vim.api.nvim_set_hl(0, "CursorIM", {reverse = true})
    vim.api.nvim_set_hl(0, "CursorColumn", {bg = "#31353f"})
    vim.api.nvim_set_hl(0, "CursorLine", {bg = "#31353f"})
    vim.api.nvim_set_hl(0, "ColorColumn", {bg = "#31353f"})
    vim.api.nvim_set_hl(0, "CursorLineNr", {fg = "#abb2bf"})
    vim.api.nvim_set_hl(0, "LineNr", {fg = "#5c6370"})
    vim.api.nvim_set_hl(0, "Conceal", {fg = "#5c6370", bg = "#31353f"})
    vim.api.nvim_set_hl(0, "DiffAdd", {fg = "none", bg = "#31392b"})
    vim.api.nvim_set_hl(0, "DiffChange", {fg = "none", bg = "#1c3448"})
    vim.api.nvim_set_hl(0, "DiffDelete", {fg = "none", bg = "#382b2c"})
    vim.api.nvim_set_hl(0, "DiffText", {fg = "none", bg = "#2c5372"})
    vim.api.nvim_set_hl(0, "DiffAdded", {fg = "#98c379"})
    vim.api.nvim_set_hl(0, "DiffRemoved", {fg = "#e86671"})
    vim.api.nvim_set_hl(0, "DiffFile", {fg = "#56b6c2"})
    vim.api.nvim_set_hl(0, "DiffIndexLine", {fg = "#5c6370"})
    vim.api.nvim_set_hl(0, "Directory", {fg = "#61afef"})
    vim.api.nvim_set_hl(0, "ErrorMsg", {fg = "#e86671", bold = true})
    vim.api.nvim_set_hl(0, "WarningMsg", {fg = "#e5c07b", bold = true})
    vim.api.nvim_set_hl(0, "MoreMsg", {fg = "#61afef", bold = true})
    vim.api.nvim_set_hl(0, "ModeMsg", {fg = "#98c379"})
    vim.api.nvim_set_hl(0, "IncSearch", {fg = "#282c34", bg = "#d19a66"})
    vim.api.nvim_set_hl(0, "Search", {fg = "#282c34", bg = "#ebd09c"})
    vim.api.nvim_set_hl(0, "Substitute", {fg = "#282c34", bg = "#98c379"})
    vim.api.nvim_set_hl(0, "MatchParen", {fg = "none", bg = "#5c6370"})
    vim.api.nvim_set_hl(0, "NonText", {fg = "#5c6370"})
    vim.api.nvim_set_hl(0, "Whitespace", {fg = "#5c6370"})
    vim.api.nvim_set_hl(0, "SpecialKey", {fg = "#5c6370"})
    vim.api.nvim_set_hl(0, "Pmenu", {fg = "#abb2bf", bg = "#31353f"})
    vim.api.nvim_set_hl(0, "PmenuSbar", {fg = "none", bg = "#31353f"})
    vim.api.nvim_set_hl(0, "PmenuSel", {fg = "#282c34", bg = "#73b8f1"})
    vim.api.nvim_set_hl(0, "WildMenu", {fg = "#282c34", bg = "#61afef"})
    vim.api.nvim_set_hl(0, "PmenuThumb", {fg = "none", bg = "#5c6370"})
    vim.api.nvim_set_hl(0, "Question", {fg = "#e5c07b"})
    vim.api.nvim_set_hl(0, "SpellBad", {fg = "#e86671", underline = true, sp = "#e86671"})
    vim.api.nvim_set_hl(0, "SpellCap", {fg = "#e5c07b", underline = true, sp = "#e5c07b"})
    vim.api.nvim_set_hl(0, "SpellLocal", {fg = "#61afef", underline = true, sp = "#61afef"})
    vim.api.nvim_set_hl(0, "SpellRare", {fg = "#c678dd", underline = true, sp = "#c678dd"})
    vim.api.nvim_set_hl(0, "StatusLine", {fg = "#abb2bf", bg = "#393f4a"})
    vim.api.nvim_set_hl(0, "StatusLineTerm", {fg = "#abb2bf", bg = "#393f4a"})
    vim.api.nvim_set_hl(0, "StatusLineNC", {fg = "#5c6370", bg = "#31353f"})
    vim.api.nvim_set_hl(0, "StatusLineTermNC", {fg = "#5c6370", bg = "#31353f"})
    vim.api.nvim_set_hl(0, "TabLine", {fg = "#abb2bf", bg = "#31353f"})
    vim.api.nvim_set_hl(0, "TabLineFill", {fg = "#5c6370", bg = "#31353f"})
    vim.api.nvim_set_hl(0, "TabLineSel", {fg = "#282c34", bg = "#abb2bf"})
    vim.api.nvim_set_hl(0, "VertSplit", {fg = "#3b3f4c"})
    vim.api.nvim_set_hl(0, "Visual", {bg = "#3b3f4c"})
    vim.api.nvim_set_hl(0, "VisualNOS", {fg = "none", bg = "#393f4a", underline = true})
    vim.api.nvim_set_hl(0, "QuickFixLine", {fg = "#61afef", underline = true})
    vim.api.nvim_set_hl(0, "Debug", {fg = "#e5c07b"})
    vim.api.nvim_set_hl(0, "debugPC", {fg = "#282c34", bg = "#98c379"})
    vim.api.nvim_set_hl(0, "debugBreakpoint", {fg = "#282c34", bg = "#e86671"})
    vim.api.nvim_set_hl(0, "ToolbarButton", {fg = "#282c34", bg = "#73b8f1"})
    vim.api.nvim_set_hl(0, "FloatBorder", {fg = "#5c6370", bg = "#31353f"})
    vim.api.nvim_set_hl(0, "NormalFloat", {fg = "#abb2bf", bg = "#31353f"})
    vim.api.nvim_set_hl(0, "WinSeparator", {link = "VertSplit"})
    vim.api.nvim_set_hl(0, "WinBar", {link = "StatusLine"})
    vim.api.nvim_set_hl(0, "WinBarNC", {link = "StatusLineNC"})
    return true
  end
  local function _4_()
    vim.api.nvim_set_hl(0, "GitSignsAdd", {fg = "#98c379"})
    vim.api.nvim_set_hl(0, "GitSignsAddLn", {fg = "#98c379"})
    vim.api.nvim_set_hl(0, "GitSignsAddNr", {fg = "#98c379"})
    vim.api.nvim_set_hl(0, "GitSignsChange", {fg = "#61afef"})
    vim.api.nvim_set_hl(0, "GitSignsChangeLn", {fg = "#61afef"})
    vim.api.nvim_set_hl(0, "GitSignsChangeNr", {fg = "#61afef"})
    vim.api.nvim_set_hl(0, "GitSignsDelete", {fg = "#e86671"})
    vim.api.nvim_set_hl(0, "GitSignsDeleteLn", {fg = "#e86671"})
    vim.api.nvim_set_hl(0, "GitSignsDeleteNr", {fg = "#e86671"})
    return true
  end
  local function _5_()
    vim.api.nvim_set_hl(0, "LspCxxHlGroupEnumConstant", {fg = "#d19a66"})
    vim.api.nvim_set_hl(0, "LspCxxHlGroupMemberVariable", {fg = "#d19a66"})
    vim.api.nvim_set_hl(0, "LspCxxHlGroupNamespace", {fg = "#61afef"})
    vim.api.nvim_set_hl(0, "LspCxxHlSkippedRegion", {fg = "#5c6370"})
    vim.api.nvim_set_hl(0, "LspCxxHlSkippedRegionBeginEnd", {fg = "#e86671"})
    vim.api.nvim_set_hl(0, "DiagnosticError", {fg = "#e86671"})
    vim.api.nvim_set_hl(0, "DiagnosticHint", {fg = "#c678dd"})
    vim.api.nvim_set_hl(0, "DiagnosticInfo", {fg = "#56b6c2"})
    vim.api.nvim_set_hl(0, "DiagnosticWarn", {fg = "#e5c07b"})
    vim.api.nvim_set_hl(0, "DiagnosticVirtualTextError", {bg = 3353909, fg = "#993939"})
    vim.api.nvim_set_hl(0, "DiagnosticVirtualTextWarn", {bg = 3355186, fg = "#93691d"})
    vim.api.nvim_set_hl(0, "DiagnosticVirtualTextInfo", {bg = 2634555, fg = "#2b6f77"})
    vim.api.nvim_set_hl(0, "DiagnosticVirtualTextHint", {bg = 3288639, fg = "#8a3fa0"})
    vim.api.nvim_set_hl(0, "DiagnosticUnderlineError", {undercurl = true, sp = "#e86671"})
    vim.api.nvim_set_hl(0, "DiagnosticUnderlineHint", {undercurl = true, sp = "#c678dd"})
    vim.api.nvim_set_hl(0, "DiagnosticUnderlineInfo", {undercurl = true, sp = "#61afef"})
    vim.api.nvim_set_hl(0, "DiagnosticUnderlineWarn", {undercurl = true, sp = "#e5c07b"})
    vim.api.nvim_set_hl(0, "LspReferenceText", {bg = "#393f4a"})
    vim.api.nvim_set_hl(0, "LspReferenceWrite", {bg = "#393f4a"})
    vim.api.nvim_set_hl(0, "LspReferenceRead", {bg = "#393f4a"})
    vim.api.nvim_set_hl(0, "LspCodeLens", {fg = "#5c6370", italic = true})
    vim.api.nvim_set_hl(0, "LspCodeLensSeparator", {fg = "#5c6370"})
    vim.api.nvim_set_hl(0, "LspDiagnosticsDefaultError", {link = "DiagnosticError"})
    vim.api.nvim_set_hl(0, "LspDiagnosticsDefaultHint", {link = "DiagnosticHint"})
    vim.api.nvim_set_hl(0, "LspDiagnosticsDefaultInformation", {link = "DiagnosticInfo"})
    vim.api.nvim_set_hl(0, "LspDiagnosticsDefaultWarning", {link = "DiagnosticWarn"})
    vim.api.nvim_set_hl(0, "LspDiagnosticsUnderlineError", {link = "DiagnosticUnderlineError"})
    vim.api.nvim_set_hl(0, "LspDiagnosticsUnderlineHint", {link = "DiagnosticUnderlineHint"})
    vim.api.nvim_set_hl(0, "LspDiagnosticsUnderlineInformation", {link = "DiagnosticUnderlineInfo"})
    vim.api.nvim_set_hl(0, "LspDiagnosticsUnderlineWarning", {link = "DiagnosticUnderlineWarn"})
    vim.api.nvim_set_hl(0, "LspDiagnosticsVirtualTextError", {link = "DiagnosticVirtualTextError"})
    vim.api.nvim_set_hl(0, "LspDiagnosticsVirtualTextWarning", {link = "DiagnosticVirtualTextWarn"})
    vim.api.nvim_set_hl(0, "LspDiagnosticsVirtualTextInformation", {link = "DiagnosticVirtualTextInfo"})
    vim.api.nvim_set_hl(0, "LspDiagnosticsVirtualTextHint", {link = "DiagnosticVirtualTextHint"})
    return true
  end
  local function _6_()
    vim.api.nvim_set_hl(0, "markdownBlockquote", {fg = "#5c6370"})
    vim.api.nvim_set_hl(0, "markdownBold", {fg = "none", bold = true})
    vim.api.nvim_set_hl(0, "markdownBoldDelimiter", {fg = "#5c6370"})
    vim.api.nvim_set_hl(0, "markdownCode", {fg = "#98c379"})
    vim.api.nvim_set_hl(0, "markdownCodeBlock", {fg = "#98c379"})
    vim.api.nvim_set_hl(0, "markdownCodeDelimiter", {fg = "#e5c07b"})
    vim.api.nvim_set_hl(0, "markdownH1", {fg = "#e86671", bold = true})
    vim.api.nvim_set_hl(0, "markdownH2", {fg = "#c678dd", bold = true})
    vim.api.nvim_set_hl(0, "markdownH3", {fg = "#d19a66", bold = true})
    vim.api.nvim_set_hl(0, "markdownH4", {fg = "#e86671", bold = true})
    vim.api.nvim_set_hl(0, "markdownH5", {fg = "#c678dd", bold = true})
    vim.api.nvim_set_hl(0, "markdownH6", {fg = "#d19a66", bold = true})
    vim.api.nvim_set_hl(0, "markdownHeadingDelimiter", {fg = "#5c6370"})
    vim.api.nvim_set_hl(0, "markdownHeadingRule", {fg = "#5c6370"})
    vim.api.nvim_set_hl(0, "markdownId", {fg = "#e5c07b"})
    vim.api.nvim_set_hl(0, "markdownIdDeclaration", {fg = "#e86671"})
    vim.api.nvim_set_hl(0, "markdownItalic", {fg = "none", italic = true})
    vim.api.nvim_set_hl(0, "markdownItalicDelimiter", {fg = "#5c6370", italic = true})
    vim.api.nvim_set_hl(0, "markdownLinkDelimiter", {fg = "#5c6370"})
    vim.api.nvim_set_hl(0, "markdownLinkText", {fg = "#e86671"})
    vim.api.nvim_set_hl(0, "markdownLinkTextDelimiter", {fg = "#5c6370"})
    vim.api.nvim_set_hl(0, "markdownListMarker", {fg = "#e86671"})
    vim.api.nvim_set_hl(0, "markdownOrderedListMarker", {fg = "#e86671"})
    vim.api.nvim_set_hl(0, "markdownRule", {fg = "#c678dd"})
    vim.api.nvim_set_hl(0, "markdownUrl", {fg = "#61afef", underline = true})
    vim.api.nvim_set_hl(0, "markdownUrlDelimiter", {fg = "#5c6370"})
    vim.api.nvim_set_hl(0, "markdownUrlTitleDelimiter", {fg = "#98c379"})
    return true
  end
  local function _7_()
    vim.api.nvim_set_hl(0, "String", {fg = "#98c379"})
    vim.api.nvim_set_hl(0, "Character", {fg = "#d19a66"})
    vim.api.nvim_set_hl(0, "Number", {fg = "#d19a66"})
    vim.api.nvim_set_hl(0, "Float", {fg = "#d19a66"})
    vim.api.nvim_set_hl(0, "Boolean", {fg = "#d19a66"})
    vim.api.nvim_set_hl(0, "Type", {fg = "#e5c07b"})
    vim.api.nvim_set_hl(0, "Structure", {fg = "#e5c07b"})
    vim.api.nvim_set_hl(0, "StorageClass", {fg = "#e5c07b"})
    vim.api.nvim_set_hl(0, "Identifier", {fg = "#e86671"})
    vim.api.nvim_set_hl(0, "Constant", {fg = "#56b6c2"})
    vim.api.nvim_set_hl(0, "PreProc", {fg = "#c678dd"})
    vim.api.nvim_set_hl(0, "PreCondit", {fg = "#c678dd"})
    vim.api.nvim_set_hl(0, "Include", {fg = "#c678dd"})
    vim.api.nvim_set_hl(0, "Keyword", {fg = "#c678dd"})
    vim.api.nvim_set_hl(0, "Define", {fg = "#c678dd"})
    vim.api.nvim_set_hl(0, "Typedef", {fg = "#c678dd"})
    vim.api.nvim_set_hl(0, "Exception", {fg = "#c678dd"})
    vim.api.nvim_set_hl(0, "Conditional", {fg = "#c678dd"})
    vim.api.nvim_set_hl(0, "Repeat", {fg = "#c678dd"})
    vim.api.nvim_set_hl(0, "Statement", {fg = "#c678dd"})
    vim.api.nvim_set_hl(0, "Macro", {fg = "#e86671"})
    vim.api.nvim_set_hl(0, "Error", {fg = "#c678dd"})
    vim.api.nvim_set_hl(0, "Label", {fg = "#c678dd"})
    vim.api.nvim_set_hl(0, "Special", {fg = "#e86671"})
    vim.api.nvim_set_hl(0, "SpecialChar", {fg = "#e86671"})
    vim.api.nvim_set_hl(0, "Function", {fg = "#61afef"})
    vim.api.nvim_set_hl(0, "Operator", {fg = "#c678dd"})
    vim.api.nvim_set_hl(0, "Title", {fg = "#56b6c2"})
    vim.api.nvim_set_hl(0, "Tag", {fg = "#98c379"})
    vim.api.nvim_set_hl(0, "Delimiter", {fg = "#848b98"})
    vim.api.nvim_set_hl(0, "Comment", {fg = "#5c6370", italic = true})
    vim.api.nvim_set_hl(0, "SpecialComment", {fg = "#5c6370", italic = true})
    vim.api.nvim_set_hl(0, "Todo", {fg = "#e86671", italic = true})
    return true
  end
  local function _8_()
    vim.api.nvim_set_hl(0, "TelescopeBorder", {fg = "#e86671"})
    vim.api.nvim_set_hl(0, "TelescopePromptBorder", {fg = "#56b6c2"})
    vim.api.nvim_set_hl(0, "TelescopeResultsBorder", {fg = "#56b6c2"})
    vim.api.nvim_set_hl(0, "TelescopePreviewBorder", {fg = "#56b6c2"})
    vim.api.nvim_set_hl(0, "TelescopeMatching", {fg = "#d19a66", bold = true})
    vim.api.nvim_set_hl(0, "TelescopePromptPrefix", {fg = "#98c379"})
    vim.api.nvim_set_hl(0, "TelescopeSelection", {bg = "#393f4a"})
    vim.api.nvim_set_hl(0, "TelescopeSelectionCaret", {fg = "#e5c07b"})
    return true
  end
  local function _9_()
    vim.api.nvim_set_hl(0, "TSAnnotation", {fg = "#abb2bf"})
    vim.api.nvim_set_hl(0, "TSAttribute", {fg = "#56b6c2"})
    vim.api.nvim_set_hl(0, "TSBoolean", {fg = "#d19a66"})
    vim.api.nvim_set_hl(0, "TSCharacter", {fg = "#d19a66"})
    vim.api.nvim_set_hl(0, "TSComment", {fg = "#5c6370", italic = true})
    vim.api.nvim_set_hl(0, "TSConditional", {fg = "#c678dd"})
    vim.api.nvim_set_hl(0, "TSConstant", {fg = "#d19a66"})
    vim.api.nvim_set_hl(0, "TSConstBuiltin", {fg = "#d19a66"})
    vim.api.nvim_set_hl(0, "TSConstMacro", {fg = "#d19a66"})
    vim.api.nvim_set_hl(0, "TSConstructor", {fg = "#e5c07b", bold = true})
    vim.api.nvim_set_hl(0, "TSError", {fg = "#abb2bf"})
    vim.api.nvim_set_hl(0, "TSException", {fg = "#c678dd"})
    vim.api.nvim_set_hl(0, "TSField", {fg = "#56b6c2"})
    vim.api.nvim_set_hl(0, "TSFloat", {fg = "#d19a66"})
    vim.api.nvim_set_hl(0, "TSFunction", {fg = "#61afef"})
    vim.api.nvim_set_hl(0, "TSFuncBuiltin", {fg = "#56b6c2"})
    vim.api.nvim_set_hl(0, "TSFuncMacro", {fg = "#56b6c2"})
    vim.api.nvim_set_hl(0, "TSInclude", {fg = "#c678dd"})
    vim.api.nvim_set_hl(0, "TSKeyword", {fg = "#c678dd"})
    vim.api.nvim_set_hl(0, "TSKeywordFunction", {fg = "#c678dd"})
    vim.api.nvim_set_hl(0, "TSKeywordOperator", {fg = "#c678dd"})
    vim.api.nvim_set_hl(0, "TSLabel", {fg = "#e86671"})
    vim.api.nvim_set_hl(0, "TSMethod", {fg = "#61afef"})
    vim.api.nvim_set_hl(0, "TSNamespace", {fg = "#e5c07b"})
    vim.api.nvim_set_hl(0, "TSNone", {fg = "#abb2bf"})
    vim.api.nvim_set_hl(0, "TSNumber", {fg = "#d19a66"})
    vim.api.nvim_set_hl(0, "TSOperator", {fg = "#abb2bf"})
    vim.api.nvim_set_hl(0, "TSParameter", {fg = "#e86671"})
    vim.api.nvim_set_hl(0, "TSParameterReference", {fg = "#abb2bf"})
    vim.api.nvim_set_hl(0, "TSProperty", {fg = "#56b6c2"})
    vim.api.nvim_set_hl(0, "TSPunctDelimiter", {fg = "#848b98"})
    vim.api.nvim_set_hl(0, "TSPunctBracket", {fg = "#848b98"})
    vim.api.nvim_set_hl(0, "TSPunctSpecial", {fg = "#e86671"})
    vim.api.nvim_set_hl(0, "TSRepeat", {fg = "#c678dd"})
    vim.api.nvim_set_hl(0, "TSString", {fg = "#98c379"})
    vim.api.nvim_set_hl(0, "TSStringRegex", {fg = "#d19a66"})
    vim.api.nvim_set_hl(0, "TSStringEscape", {fg = "#e86671"})
    vim.api.nvim_set_hl(0, "TSSymbol", {fg = "#56b6c2"})
    vim.api.nvim_set_hl(0, "TSTag", {fg = "#e86671"})
    vim.api.nvim_set_hl(0, "TSTagDelimiter", {fg = "#e86671"})
    vim.api.nvim_set_hl(0, "TSText", {fg = "#abb2bf"})
    vim.api.nvim_set_hl(0, "TSStrong", {fg = "#abb2bf", bold = true})
    vim.api.nvim_set_hl(0, "TSEmphasis", {fg = "#abb2bf", italic = true})
    vim.api.nvim_set_hl(0, "TSUnderline", {fg = "#abb2bf", underline = true})
    vim.api.nvim_set_hl(0, "TSStrike", {fg = "#abb2bf", strikethrough = true})
    vim.api.nvim_set_hl(0, "TSTitle", {fg = "#d19a66", bold = true})
    vim.api.nvim_set_hl(0, "TSLiteral", {fg = "#98c379"})
    vim.api.nvim_set_hl(0, "TSURI", {fg = "#56b6c2", underline = true})
    vim.api.nvim_set_hl(0, "TSMath", {fg = "#abb2bf"})
    vim.api.nvim_set_hl(0, "TSTextReference", {fg = "#61afef"})
    vim.api.nvim_set_hl(0, "TSEnviroment", {fg = "#abb2bf"})
    vim.api.nvim_set_hl(0, "TSEnviromentName", {fg = "#abb2bf"})
    vim.api.nvim_set_hl(0, "TSNote", {fg = "#abb2bf"})
    vim.api.nvim_set_hl(0, "TSWarning", {fg = "#abb2bf"})
    vim.api.nvim_set_hl(0, "TSDanger", {fg = "#abb2bf"})
    vim.api.nvim_set_hl(0, "TSType", {fg = "#e5c07b"})
    vim.api.nvim_set_hl(0, "TSTypeBuiltin", {fg = "#d19a66"})
    vim.api.nvim_set_hl(0, "TSVariable", {fg = "#abb2bf"})
    vim.api.nvim_set_hl(0, "@variable", {link = "Identifier"})
    vim.api.nvim_set_hl(0, "TSVariableBuiltin", {fg = "#e86671"})
    return true
  end
  M_3_auto = {cmp = _2_, common = _3_, gitsigns = _4_, lsp = _5_, markdown = _6_, syntax = _7_, telescope = _8_, treesitter = _9_}
  local function _10_()
    M_3_auto.common()
    M_3_auto.syntax()
    M_3_auto.treesitter()
    M_3_auto.lsp()
    M_3_auto.markdown()
    M_3_auto.cmp()
    M_3_auto.gitsigns()
    return M_3_auto.telescope()
  end
  M_3_auto["colorscheme"] = _10_
  return M_3_auto
end
return _1_(...)
